### ISSUE TITLE
why didn't support "hour&minutes&seconds"  

### ISSUE THREAD

**Issue by z759341385** [berkobob/Reminders#4]
At common/Reminders.swift file,line 70
` reminder.dueDateComponents = DateComponents(year: date["year"], month: date["month"], day: date["day"], hour: nil, minute: nil, second: nil )`

**Comment by berkobob** [comment]
Because I didn't need them for my project. Feel free to submit a PR

**Comment by niamatallah** [comment]
hey is it still not supported?

**Comment by hasanalaniIT** [comment]
I submitted a PR to Support

**Comment by berkobob** [comment]
Fixed by PR. Thanks @hasanalaniIT
