### ISSUE TITLE
not working working in ad hoc ios distributation ?

### ISSUE THREAD

**Issue by hosseinkhojany** [berkobob/Reminders#5]
iOS 15.7
iPhone 7
Hi! thanks for good plugin!
When I set successfully a reminder in ios it not trigger at all When I open reminder app I can see it

**Comment by berkobob** [comment]
I'm not sure what you mean. There is no real-time synching. You need to poll the API to get updates.

**Comment by hosseinkhojany** [comment]
I mean, the reminder is created correctly and I see it in the reminder app, but when we reach the promised time, the reminder is not called and I don't get a notification(A number is added on the badge icon of the reminder app, but the notification nope!), but when I manually register a new reminder in the reminder app, it works correctly, this is very strange.
`

      reminders.hasAccess().then((value) async {
        if(value){
          final RemList list = await reminders.getDefaultList() ?? RemList('Myelin Reminders');
          final reminder = Reminder(priority: 3, list: list, title: "Test", );
          reminder.dueDate = schedule;
          await reminders.saveReminder(reminder);
        }
      });
      `

**Comment by berkobob** [comment]
The app doesn’t use hours and minutes, only dates. I didn’t need time for my app. If you want to add that functionality, I’m happy for you to submit a PR.

**Comment by hosseinkhojany** [comment]
![2023-09-07 10 16 47](https://github.com/berkobob/reminders/assets/37432839/860779a0-097a-42cc-8a39-7994555618b5)

What the F*ck Is This Piece of Shit ): ?

**Comment by SethuSenthil** [comment]
Nothing wrong with the code in the screenshot. But seriously, fam, let's vibe a bit more positively.

We're all in this open-source gig voluntarily, grinding for the greater good, and nobody's cashing in on this. So, before you drop F-bombs like confetti, remember we're here to build, not burn bridges.

Take a chill pill, appreciate the hustle, and let's keep this collab drama-free. 🌐✌️
