### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by lukemmtt** [berkobob/Reminders#7]
Hi there, 
I use this plugin in my app—thanks for your work on it! I noticed that there hasn't been a new pubdev release in quite a while—may I request that a new one be issued? Or may I help towards this in some way? I currently point to the main branch to take advantage of recent contributions, but this is not ideal. 

Thank you in advance!

**Comment by berkobob** [comment]
Feel free to submit a pull request.
Antoine

**Comment by lukemmtt** [comment]
Thank you for your response Antoine. I'd like to clarify my previous message. The main branch of the plugin is in excellent shape, with valuable contributions. However, without a recent release on pub.dev, we are unable to utilize these updates in our production app unless we point directly to the main branch, which is not a preferred practice for us.

I'm not seeking to add new features but to facilitate a new release that includes the latest improvements from the main branch. If you can grant me the necessary permissions, I would be happy to assist with the release process on both GitHub and pub.dev. This would help us, and likely many others in the community, who rely on the official releases for stability in production environments.

Thanks again for considering my request.

**Comment by berkobob** [comment]
OK, I think I’ve done it. Do you want to check?

**Comment by lukemmtt** [comment]
I see a new release in [pub.dev](https://pub.dev/packages/reminders), thank you! To be clear, it looks like the latest version on pub.dev is 1.2 (uploaded 2 hours ago with release notes from September), but I'm confused because the changelog has release notes for a version 2.0.0. Maybe it's still propagating?

In any event, thanks for the quick responses, and I remain happy to help with other maintenance if you're open to it, specifically things like:
- Tagging releases in GitHub
- Change log management / documenting breaking changes
