### ISSUE TITLE
macOS permission requests fail when run from Android Studio or VScode

### ISSUE THREAD

**Issue by lukemmtt** [berkobob/reminders#8]
I was researching why my macOS Flutter build was having issues when attempting to request and utilize permissions, and I came across a number of valuable resources and open issues. I'm creating an issue here to track the underlying issue—hopefully it might save other users of the `reminders` plugin some time in troubleshooting in the future. 

- [Flutter: MacOS Permission problem in VSCode](https://github.com/flutter/flutter/issues/114352) (Open. Was opened by @berkobob,`reminders`' creator)
- [device_calendar: update Mac support #419](https://github.com/builttoroam/device_calendar/pull/419#issuecomment-1264204878) (An open PR on `device_calendar`,the most popular other Flutter calendar plugin, notably also using EventKit, where the same issue was encountered.) 
- [Flutter: Macos app doesn't run in sandbox when using flutter run](https://github.com/flutter/flutter/issues/122796) (Closed, unresolved. Good summary. Created in relation to the device_calendar PR. )
- [Flutter: Fails to Load Info.plist in macOS with vscode and Android Studio](https://github.com/flutter/flutter/issues/134191#issuecomment-1740117608) (Open. Seems like a strong lead on what the root cause is here.)

For what it's worth, my workflow for debugging anything involving Calendar or Reminders macOS permissions right now is:
1. Launch debug or release build from Android Studio. Permissions will not work at this stage, and any attempt to read permission will return PermissionStatus at the OS level.
2. Ensure the launcher icon is saved in the dock, then close the app & reopen it by clicking on icon in dock
3. Permissions work as expected.

**Comment by berkobob** [comment]
I know this works in VS Code but I haven't tried it in Android Studio. Open a terminal within your IDE and run this code:

```
osascript - title <<END
on run a
tell app "Reminders"
tell list "Reminders" of default account
make new reminder with properties {name:item 1 of a}
end
end
end
END
```

This will create a reminder and give your IDE permission.
